using System.Collections.Generic;
using System.Linq;
using Mono.Cecil;
using Mono.Cecil.Cil;
using SuperSync.CodeGen.Data;
using SuperSync.CodeGen.Utils;

namespace SuperSync.CodeGen
{
    public static class CodeWeaver
    {
        public static WeavedProperty WeaveProperty(
            TypeDefinition type,
            PropertyWithSyncAttribute propertyWithSyncAttribute,
            ModuleDefinition module,
            ModuleReferences moduleReferences)
        {
            var result = new WeavedProperty { PropertyWithSyncAttribute = propertyWithSyncAttribute };

            // Figure out what we want the T1 in NetworkVariable<T1> to be
            // If we're handling a NetworkObject or NetworkBehaviour, we want to use their wrappers
            TypeReference t1;
            if (propertyWithSyncAttribute.IsDerivedFromNetworkBehaviour)
                t1 = moduleReferences.NetworkBehaviourReference;
            else if (propertyWithSyncAttribute.IsDerivedFromNetworkObject)
                t1 = moduleReferences.NetworkObjectReference;
            else
                t1 = module.ImportReference(propertyWithSyncAttribute.Property.PropertyType);

            // Get references to (Anticipated)NetworkVariable<T1> methods
            result.NetworkVariableReferences =
                new NetworkVariableReferences(module, moduleReferences, t1,
                    propertyWithSyncAttribute.ShouldCreateAnticipatedVariable);

            // Create the "backing field" of type NetworkVariable we're going to use
            result.WeavedBackingField = new FieldDefinition($"__Netvar_{propertyWithSyncAttribute.Property.Name}",
                FieldAttributes.Private,
                result.NetworkVariableReferences.NetworkVariableT1);
            type.Fields.Add(result.WeavedBackingField);

            // Edit the setter body
            {
                var processor = propertyWithSyncAttribute
                    .Property
                    .SetMethod
                    .Body
                    .GetILProcessor();

                processor.Clear();

                // 'this.__Netvar_property' ...
                processor.Emit(OpCodes.Ldarg_0); // Load instance 'this'
                processor.Emit(OpCodes.Ldfld, result.WeavedBackingField); // Load field '__Netvar_<property>'
                processor.Emit(OpCodes.Ldarg_1); // Load setter argument 1 'value'

                // Emit wrapper for the value if required
                if (propertyWithSyncAttribute.RequiresWrapper)
                {
                    processor.Emit(OpCodes.Call,
                        propertyWithSyncAttribute
                            .GetWrapperConversionFunctionReturningWrapperType(moduleReferences));
                }

                if (propertyWithSyncAttribute.ShouldCreateAnticipatedVariable)
                {
                    // ... '.Anticipate(value)'
                    processor.Emit(OpCodes.Callvirt,
                        result.NetworkVariableReferences.AnticipatedNetworkVariableT1_Anticipate);
                }
                else
                {
                    // ... '= value'
                    processor.Emit(OpCodes.Callvirt, result.NetworkVariableReferences.NetworkVariableT1_Setter);
                }

                // 'return'
                processor.Emit(OpCodes.Ret);
            }

            // Edit the getter body
            {
                var processor = propertyWithSyncAttribute
                    .Property
                    .GetMethod
                    .Body
                    .GetILProcessor();

                processor.Clear();

                // Emit 'this.__Netvar_property.Value' ...
                processor.Emit(OpCodes.Ldarg_0); // Load instance 'this'
                processor.Emit(OpCodes.Ldfld, result.WeavedBackingField); // Load field '__Netvar_<property>'
                processor.Emit(OpCodes.Callvirt,
                    result.NetworkVariableReferences.NetworkVariableT1_Getter); // Call NetworkVariable<T1>.Value

                // Emit wrapper for the value if required
                if (propertyWithSyncAttribute.RequiresWrapper)
                {
                    // Transforms flow into 'wrapper(this.__Netvar_property.Value)'
                    processor.Emit(OpCodes.Call,
                        propertyWithSyncAttribute
                            .GetWrapperConversionFunctionReturningPropertyType(moduleReferences));
                }

                // Emit 'return'
                processor.Emit(OpCodes.Ret);
            }

            // Synced properties have their own backing fields generated by the compiler
            // We need to:
            // 1. find out if they're being set in the constructor and find the value it's being set to
            // 2. remove them from the type
            // Find the part of the constructor that sets the native backing field and remove it
            {
                var constructor = type.GetOrCreateConstructor();

                var processor = constructor
                    .Body
                    .GetILProcessor();

                // Find the last instruction of the set operation (Stfld)
                Instruction setInstruction = null;
                foreach (var bodyInstruction in processor.Body.Instructions.Where(bodyInstruction =>
                             bodyInstruction.OpCode == OpCodes.Stfld))
                {
                    if (bodyInstruction.Operand is not FieldDefinition fieldDefinition)
                        continue;

                    if (fieldDefinition.Name != $"<{propertyWithSyncAttribute.Property.Name}>k__BackingField")
                        continue;

                    result.NativeBackingField = module.ImportReference(fieldDefinition);
                    result.NativeBackingField.FieldType = module.ImportReference(result.NativeBackingField.FieldType);

                    setInstruction = bodyInstruction;
                }

                if (setInstruction != null)
                {
                    // Get all the instructions responsible for setting the native backing field
                    // Reads all instructions above the Stfld until the Ldarg_0 (load 'this') - includes stack pushes etc
                    result.NativeBackingFieldCtorBody = setInstruction.EnumerateBackwardsUntilAndIncluding(v =>
                        v.OpCode != OpCodes.Ldarg_0).Reverse().ToArray();

                    // Remove the instructions from the constructor body
                    foreach (var instruction in result.NativeBackingFieldCtorBody)
                        processor.Remove(instruction);
                }
            }

            // If we didn't find the native backing field from the constructor, find it now
            result.NativeBackingField ??= module.ImportReference(type.Fields.FirstOrDefault(v =>
                v.Name == $"<{propertyWithSyncAttribute.Property.Name}>k__BackingField"));
            result.NativeBackingField.FieldType = module.ImportReference(result.NativeBackingField.FieldType);

            // Remove the native backing field from the type
            type.Fields.Remove(result.NativeBackingField.Resolve());

            return result;
        }

        public static void WeaveConstructor(
            TypeDefinition type,
            List<WeavedProperty> weavedProperties,
            ModuleDefinition module,
            ModuleReferences moduleReferences)
        {
            var constructor = type.GetOrCreateConstructor();

            var processor = constructor
                .Body
                .GetILProcessor();

            var newInstructions = new List<Instruction>();

            // Find where the existing IL calls the base type
            // As the base type constructor will eventually initialize NetworkVariables, we need to work before it
            var callBaseCtorInstruction = processor.FindCtorCallInstruction();

            // We'll handle default values by storing them in a local variable initially - this makes the IL easier
            var localVariables = new Dictionary<TypeReference, VariableDefinition>();

            foreach (var weavedProperty in weavedProperties)
            {
                VariableDefinition localVariableForDefaultValue = null;

                // Attempt to transform the native backing field ctor code
                if (weavedProperty.NativeBackingFieldCtorBody != null)
                {
                    // If the first instruction is Ldarg_0 (load 'this'), remove it
                    if (weavedProperty.NativeBackingFieldCtorBody.Any() &&
                        weavedProperty.NativeBackingFieldCtorBody[0].OpCode == OpCodes.Ldarg_0)
                    {
                        weavedProperty.NativeBackingFieldCtorBody[0] = null;
                    }

                    // Create or reuse a local variable to store the default value in
                    if (!localVariables.TryGetValue(weavedProperty.PropertyWithSyncAttribute.Property.PropertyType,
                            out localVariableForDefaultValue))
                    {
                        // Create a new variable
                        localVariableForDefaultValue =
                            new VariableDefinition(weavedProperty.PropertyWithSyncAttribute.Property.PropertyType);
                        constructor.Body.Variables.Add(localVariableForDefaultValue);
                        localVariables[weavedProperty.PropertyWithSyncAttribute.Property.PropertyType] =
                            localVariableForDefaultValue;
                    }

                    // Emit code to set the local variable
                    for (var index = 0; index < weavedProperty.NativeBackingFieldCtorBody.Length; index++)
                    {
                        var instruction = weavedProperty.NativeBackingFieldCtorBody[index];

                        // If this is the last instruction, and it's a Stfld replace it with a Stloc_S
                        if (index == weavedProperty.NativeBackingFieldCtorBody.Length - 1 &&
                            instruction.OpCode == OpCodes.Stfld)
                        {
                            instruction.OpCode = OpCodes.Stloc_S;
                            instruction.Operand = localVariableForDefaultValue;
                        }

                        newInstructions.Add(instruction);
                    }
                }

                // Emit instructions to initialize the property
                newInstructions.Add(processor.Create(OpCodes.Ldarg_0)); // Load instance 'this'

                // Emit wrapper code if necessary
                if (weavedProperty.PropertyWithSyncAttribute.RequiresWrapper)
                {
                    var wrapperType = weavedProperty.PropertyWithSyncAttribute.GetWrapperType(moduleReferences);
                    var wrapperLocalVariable = new VariableDefinition(wrapperType);
                    constructor.Body.Variables.Add(wrapperLocalVariable);

                    newInstructions.Add(processor.Create(OpCodes.Ldloca_S, wrapperLocalVariable));

                    if (localVariableForDefaultValue != null)
                    {
                        // Pass the default value variable to argument 1 of the wrapper constructor
                        newInstructions.Add(processor.Create(OpCodes.Ldloc_S, localVariableForDefaultValue));
                        newInstructions.Add(processor.Create(OpCodes.Newobj, wrapperType));
                    }
                    else
                    {
                        newInstructions.Add(processor.Create(OpCodes.Initobj, wrapperType));
                    }

                    // Pass the wrapper variable to argument 1 of the NetworkVariable constructor
                    newInstructions.Add(processor.Create(OpCodes.Ldloc_S, wrapperLocalVariable));
                }
                else
                {
                    // If we have a default value,
                    // pass the default value variable to argument 1 of the NetworkVariable constructor
                    if (localVariableForDefaultValue != null)
                    {
                        newInstructions.Add(processor.Create(OpCodes.Ldloc_S, localVariableForDefaultValue));
                    }
                    else
                    {
                        // We don't have a default value
                        // Push a valid default value for this type onto the stack
                        foreach (var instruction in weavedProperty
                                     .PropertyWithSyncAttribute
                                     .Property
                                     .PropertyType
                                     .GetLoadDefaultInstructions(module))
                        {
                            newInstructions.Add(instruction);
                        }
                    }
                }

                if (weavedProperty.PropertyWithSyncAttribute.ShouldCreateAnticipatedVariable)
                {
                    // Emit secondary arguments for AnticipatedNetworkVariable<T1>
                    // See what AnticipatedNetworkVariable constructor argument 2 (StaleDataHandling) should be
                    newInstructions.Add(processor.Create(OpCodes.Ldc_I4, 0));
                }
                else
                {
                    // Emit secondary arguments for NetworkVariable<T1>
                    // See what NetworkVariable constructor argument 2 (read permissions) should be
                    newInstructions.Add(processor.Create(OpCodes.Ldc_I4,
                        (int)weavedProperty.PropertyWithSyncAttribute.SyncFlags
                            .ToReadPermission()));

                    // See what NetworkVariable constructor argument 3 (write permissions) should be
                    newInstructions.Add(processor.Create(OpCodes.Ldc_I4,
                        (int)weavedProperty.PropertyWithSyncAttribute.SyncFlags
                            .ToWritePermission()));
                }

                // Create the NetworkVariable
                newInstructions.Add(processor.Create(OpCodes.Newobj,
                    weavedProperty.NetworkVariableReferences.NetworkVariableT1_Constructor));

                // Set the weaved backing field
                newInstructions.Add(processor.Create(OpCodes.Stfld, weavedProperty.WeavedBackingField));
            }

            // Add the new instructions
            // We need to add them before the base ctor call
            processor.CopyBefore(callBaseCtorInstruction, newInstructions);
        }

        public static void WeaveAllReplaceableCalls(TypeDefinition type,
            List<WeavedProperty> weavedProperties,
            ModuleDefinition module,
            ModuleReferences moduleReferences)
        {
            foreach (var methodDefinition in type.Methods)
            {
                var processor = methodDefinition
                    .Body
                    .GetILProcessor();

                for (var index = processor.Body.Instructions.Count - 1; index >= 0; index--)
                {
                    var callGetVariableInstruction = processor.Body.Instructions[index];
                    if (callGetVariableInstruction.OpCode != OpCodes.Call)
                        continue;

                    if (callGetVariableInstruction.Operand is not MethodReference methodReference)
                        continue;

                    // If we compare these with any more specificity we'll not find it
                    if (methodReference.DeclaringType.Name != moduleReferences.SyncUtils.Name ||
                        (methodReference.Name != moduleReferences.SyncUtils_GetVariableT1_retNetworkVariableT1.Name &&
                         methodReference.Name != moduleReferences
                             .SyncUtils_GetAnticipatedVariableT1_retAnticipatedNetworkVariableT1.Name))
                        continue;

                    // We found the call!
                    // Here's a little explanation for what we're doing here
                    // If we have a sync var defined as "[Sync] public int MySyncVar {get; set;}",
                    // in a non-static type called "TypeExample",
                    // and we write this statement: "var a = SyncUtils.GetVariable(MySyncVar)"
                    // We get this IL:
                    // "ldarg.0" - load 'this' on to the stack
                    // "call" "TypeExample::get_MySyncVar" - get the value in MySyncVar by running its getter,
                    //      put it on the stack
                    // "call" "SuperSync::GetVariable<NetworkVariable<int>>" - get the value returned by GetVariable,
                    //      put on the stack
                    // "stloc.0" - set our local variable (which is 'a') to be the value returned by GetVariable

                    // We don't really want that to happen though, and we want GetVariable to return the NetworkVariable
                    // that's behind the sync variable 'MySyncVar'

                    if (callGetVariableInstruction.Previous is not { } callPropertyGetterInstruction ||
                        callPropertyGetterInstruction.OpCode != OpCodes.Call ||
                        callPropertyGetterInstruction.Operand is not MethodReference propertyGetterReference)
                    {
                        // Unexpected instruction prior to the call
                        continue;
                    }

                    // Let's find the property used in argument 1 of GetVariable()
                    var weavedProperty = weavedProperties.FirstOrDefault(v =>
                        v.PropertyWithSyncAttribute.Property.GetMethod.Name == propertyGetterReference.Name);

                    if (weavedProperty.PropertyWithSyncAttribute == null)
                        continue;

                    // Make sure the user is using the right GetVariable function
                    if (weavedProperty.PropertyWithSyncAttribute.ShouldCreateAnticipatedVariable &&
                        methodReference.Name != moduleReferences
                            .SyncUtils_GetAnticipatedVariableT1_retAnticipatedNetworkVariableT1.Name)
                    {
                        continue; // They should be using GetAnticipatedVariable
                    }

                    // Save the instructions directly after the calls, then remove the calls
                    var instructionAfterCalls = callGetVariableInstruction.Next;
                    processor.Remove(callGetVariableInstruction);
                    processor.Remove(callPropertyGetterInstruction);

                    // Add an instruction that pushes the backing field to the stack before the instruction we saved
                    processor.InsertBefore(instructionAfterCalls,
                        processor.Create(OpCodes.Ldfld, weavedProperty.WeavedBackingField));
                }
            }
        }
    }
}