using System.Collections.Generic;
using System.Linq;
using Mono.Cecil;
using Mono.Cecil.Cil;
using SuperSync.CodeGen.Data;
using SuperSync.CodeGen.Utils;

namespace SuperSync.CodeGen
{
    public static class CodeWeaver
    {
        public static WeavedProperty WeaveProperty(
            TypeDefinition type,
            PropertyWithSyncAttribute propertyWithSyncAttribute,
            ModuleDefinition module,
            ModuleReferences moduleReferences)
        {
            var result = new WeavedProperty { PropertyWithSyncAttribute = propertyWithSyncAttribute };

            // Figure out what we want the T1 in NetworkVariable<T1> to be
            // If we're handling a NetworkObject or NetworkBehaviour, we want to use their wrappers
            TypeReference networkVariableT1;
            if (propertyWithSyncAttribute.IsDerivedFromNetworkBehaviour)
                networkVariableT1 = moduleReferences.NetworkBehaviourReference;
            else if (propertyWithSyncAttribute.IsDerivedFromNetworkObject)
                networkVariableT1 = moduleReferences.NetworkObjectReference;
            else
                networkVariableT1 = module.ImportReference(propertyWithSyncAttribute.Property.PropertyType);

            // Get references to NetworkVariable<T1> methods
            result.NetworkVariableReferences =
                new NetworkVariableReferences(module, moduleReferences, networkVariableT1);

            // Create the "backing field" of type NetworkVariable we're going to use
            result.WeavedBackingField = new FieldDefinition($"__Netvar_{propertyWithSyncAttribute.Property.Name}",
                FieldAttributes.Private,
                result.NetworkVariableReferences.NetworkVariableWithT1Reference);
            type.Fields.Add(result.WeavedBackingField);

            // Edit the setter body
            {
                var processor = propertyWithSyncAttribute
                    .Property
                    .SetMethod
                    .Body
                    .GetILProcessor();

                processor.Clear();

                // 'this.__Netvar_property' ...
                processor.Emit(OpCodes.Ldarg_0); // Load instance 'this'
                processor.Emit(OpCodes.Ldfld, result.WeavedBackingField); // Load field '__Netvar_<property>'
                processor.Emit(OpCodes.Ldarg_1); // Load setter argument 1 'value'

                // Emit wrapper for the value if required
                if (propertyWithSyncAttribute.RequiresWrapper)
                {
                    processor.Emit(OpCodes.Call,
                        propertyWithSyncAttribute
                            .GetWrapperConversionFunctionReturningWrapperType(moduleReferences));
                }

                // ... '= value'
                processor.Emit(OpCodes.Callvirt, result.NetworkVariableReferences.Setter);

                // 'return'
                processor.Emit(OpCodes.Ret);
            }

            // Edit the getter body
            {
                var processor = propertyWithSyncAttribute
                    .Property
                    .GetMethod
                    .Body
                    .GetILProcessor();

                processor.Clear();

                // Emit 'this.__Netvar_property.Value' ...
                processor.Emit(OpCodes.Ldarg_0); // Load instance 'this'
                processor.Emit(OpCodes.Ldfld, result.WeavedBackingField); // Load field '__Netvar_<property>'
                processor.Emit(OpCodes.Callvirt,
                    result.NetworkVariableReferences.Getter); // Call NetworkVariable<T1>.Value

                // Emit wrapper for the value if required
                if (propertyWithSyncAttribute.RequiresWrapper)
                {
                    // Transforms flow into 'wrapper(this.__Netvar_property.Value)'
                    processor.Emit(OpCodes.Call,
                        propertyWithSyncAttribute
                            .GetWrapperConversionFunctionReturningPropertyType(moduleReferences));
                }

                // Emit 'return'
                processor.Emit(OpCodes.Ret);
            }

            // Synced properties have their own backing fields generated by the compiler
            // We need to:
            // 1. find out if they're being set in the constructor and find the value it's being set to
            // 2. remove them from the type
            // Find the part of the constructor that sets the native backing field and remove it
            {
                var constructor = type.GetOrCreateConstructor();

                var processor = constructor
                    .Body
                    .GetILProcessor();

                // Find the last instruction of the set operation (Stfld)
                Instruction setInstruction = null;
                foreach (var bodyInstruction in processor.Body.Instructions.Where(bodyInstruction =>
                             bodyInstruction.OpCode == OpCodes.Stfld))
                {
                    if (bodyInstruction.Operand is not FieldDefinition fieldDefinition)
                        continue;

                    if (fieldDefinition.Name != $"<{propertyWithSyncAttribute.Property.Name}>k__BackingField")
                        continue;

                    result.NativeBackingField = module.ImportReference(fieldDefinition);
                    result.NativeBackingField.FieldType = module.ImportReference(result.NativeBackingField.FieldType);

                    setInstruction = bodyInstruction;
                }

                if (setInstruction != null)
                {
                    // Get all the instructions responsible for setting the native backing field
                    // Reads all instructions above the Stfld until the Ldarg_0 (load 'this') - includes stack pushes etc
                    result.NativeBackingFieldCtorBody = setInstruction.EnumerateBackwardsUntilAndIncluding(v =>
                        v.OpCode != OpCodes.Ldarg_0).Reverse().ToArray();

                    // Remove the instructions from the constructor body
                    foreach (var instruction in result.NativeBackingFieldCtorBody)
                        processor.Remove(instruction);
                }
            }

            // If we didn't find the native backing field from the constructor, find it now
            result.NativeBackingField ??= module.ImportReference(type.Fields.FirstOrDefault(v =>
                v.Name == $"<{propertyWithSyncAttribute.Property.Name}>k__BackingField"));
            result.NativeBackingField.FieldType = module.ImportReference(result.NativeBackingField.FieldType);

            // Remove the native backing field from the type
            type.Fields.Remove(result.NativeBackingField.Resolve());

            return result;
        }

        public static void WeaveConstructor(
            TypeDefinition type,
            List<WeavedProperty> weavedProperties,
            ModuleDefinition module,
            ModuleReferences moduleReferences)
        {
            var constructor = type.GetOrCreateConstructor();

            var processor = constructor
                .Body
                .GetILProcessor();

            var newInstructions = new List<Instruction>();

            // Find where the existing IL calls the base type
            // As the base type constructor will eventually initialize NetworkVariables, we need to work before it
            var callBaseCtorInstruction = processor.FindCtorCallInstruction();

            // We'll handle default values by storing them in a local variable initially - this makes the IL easier
            var localVariables = new Dictionary<TypeReference, VariableDefinition>();

            foreach (var weavedProperty in weavedProperties)
            {
                VariableDefinition localVariableForDefaultValue = null;

                // Attempt to transform the native backing field ctor code
                if (weavedProperty.NativeBackingFieldCtorBody != null)
                {
                    // If the first instruction is Ldarg_0 (load 'this'), remove it
                    if (weavedProperty.NativeBackingFieldCtorBody.Any() &&
                        weavedProperty.NativeBackingFieldCtorBody[0].OpCode == OpCodes.Ldarg_0)
                    {
                        weavedProperty.NativeBackingFieldCtorBody[0] = null;
                    }

                    // Create or reuse a local variable to store the default value in
                    if (!localVariables.TryGetValue(weavedProperty.PropertyWithSyncAttribute.Property.PropertyType,
                            out localVariableForDefaultValue))
                    {
                        // Create a new variable
                        localVariableForDefaultValue =
                            new VariableDefinition(weavedProperty.PropertyWithSyncAttribute.Property.PropertyType);
                        constructor.Body.Variables.Add(localVariableForDefaultValue);
                        localVariables[weavedProperty.PropertyWithSyncAttribute.Property.PropertyType] =
                            localVariableForDefaultValue;
                    }

                    // Emit code to set the local variable
                    for (var index = 0; index < weavedProperty.NativeBackingFieldCtorBody.Length; index++)
                    {
                        var instruction = weavedProperty.NativeBackingFieldCtorBody[index];

                        // If this is the last instruction, and it's a Stfld replace it with a Stloc_S
                        if (index == weavedProperty.NativeBackingFieldCtorBody.Length - 1 &&
                            instruction.OpCode == OpCodes.Stfld)
                        {
                            instruction.OpCode = OpCodes.Stloc_S;
                            instruction.Operand = localVariableForDefaultValue;
                        }

                        newInstructions.Add(instruction);
                    }
                }

                // Emit instructions to initialize the property
                newInstructions.Add(processor.Create(OpCodes.Ldarg_0)); // Load instance 'this'

                // Emit wrapper code if necessary
                if (weavedProperty.PropertyWithSyncAttribute.RequiresWrapper)
                {
                    var wrapperType = weavedProperty.PropertyWithSyncAttribute.GetWrapperType(moduleReferences);
                    var wrapperLocalVariable = new VariableDefinition(wrapperType);
                    constructor.Body.Variables.Add(wrapperLocalVariable);

                    newInstructions.Add(processor.Create(OpCodes.Ldloca_S, wrapperLocalVariable));

                    if (localVariableForDefaultValue != null)
                    {
                        // Pass the default value variable to argument 1 of the wrapper constructor
                        newInstructions.Add(processor.Create(OpCodes.Ldloc_S, localVariableForDefaultValue));
                        newInstructions.Add(processor.Create(OpCodes.Newobj, wrapperType));
                    }
                    else
                    {
                        newInstructions.Add(processor.Create(OpCodes.Initobj, wrapperType));
                    }

                    // Pass the wrapper variable to argument 1 of the NetworkVariable constructor
                    newInstructions.Add(processor.Create(OpCodes.Ldloc_S, wrapperLocalVariable));
                }
                else
                {
                    // Pass the default value variable to argument 1 of the NetworkVariable constructor
                    newInstructions.Add(localVariableForDefaultValue != null
                        ? processor.Create(OpCodes.Ldloc_S, localVariableForDefaultValue)
                        // Pass 0 to argument 1 of the NetworkVariable constructor
                        : processor.Create(OpCodes.Ldc_I4_0));
                }

                // See what NetworkVariable constructor argument 2 (read permissions) should be
                newInstructions.Add(processor.Create(OpCodes.Ldc_I4,
                    (int)weavedProperty.PropertyWithSyncAttribute.SyncFlags
                        .ToReadPermission()));

                // See what NetworkVariable constructor argument 3 (write permissions) should be
                newInstructions.Add(processor.Create(OpCodes.Ldc_I4,
                    (int)weavedProperty.PropertyWithSyncAttribute.SyncFlags
                        .ToWritePermission()));

                // Create the NetworkVariable
                newInstructions.Add(processor.Create(OpCodes.Newobj,
                    weavedProperty.NetworkVariableReferences.Constructor));

                // Set the weaved backing field
                newInstructions.Add(processor.Create(OpCodes.Stfld, weavedProperty.WeavedBackingField));
            }

            // Add the new instructions
            // We need to add them before the base ctor call
            processor.CopyBefore(callBaseCtorInstruction, newInstructions);
        }
    }
}