using System;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace SuperSync.SourceGen.AutoBehaviourSerialization;

[Generator]
public class NetworkBehaviourExtensionGenerator : ISourceGenerator
{
	public void Initialize( GeneratorInitializationContext ctx )
	{
		ctx.RegisterForSyntaxNotifications( () => new NetworkBehaviourClassSyntaxLocator() );
	}

	public void Execute( GeneratorExecutionContext ctx )
	{
		try
		{
			if ( ctx.SyntaxReceiver is not NetworkBehaviourClassSyntaxLocator locator )
				return;

			foreach ( var classDeclarationSyntax in locator.Classes )
			{
				var semanticModel = ctx.Compilation.GetSemanticModel( classDeclarationSyntax.SyntaxTree );
				var classDeclarationSymbol = semanticModel.GetDeclaredSymbol( classDeclarationSyntax );

				if ( classDeclarationSymbol is not INamedTypeSymbol namedTypeSymbol )
					continue;

				if ( namedTypeSymbol.GetBaseTypesAndThis()
				    .All( v => v.ToString() != SymbolNames.UNGO_NetworkBehaviour ) )
					continue;

				var shortName = namedTypeSymbol.Name;
				var fullName = classDeclarationSymbol.ToString();

				if ( fullName.StartsWith( "Unity." ) )
					continue;

				var generatedOutput = $@"/// <auto-generated /> 
// generated by SuperSync.SourceGen
using System;
using System.Buffers.Binary;
using Unity.Netcode;
using SuperSync.Serialization;
namespace SuperSync.Generated {{
    public static partial class GeneratedNetworkBehaviourSerializationExtensions {{
		/* Generated extension code for {shortName} */
		public static void ReadValueSafe( this FastBufferReader reader, out {fullName} x ) {{
			reader.ReadValueSafe( out NetworkBehaviour y );
			x = y as {fullName};
		}}

		/* Generated extension code for {shortName} */
		public static void WriteValueSafe( this FastBufferWriter writer, in {fullName} x) {{
			NetworkBehaviour y = x;
			writer.WriteValueSafe( y );
		}}
	}}
}}
";
				var fileName = $"{fullName}.g.cs".ToSafeGeneratedName();
				ctx.AddSource( fileName, generatedOutput );
			}
		}
		catch ( Exception ex )
		{
			// Info( ex.ToString() );
		}
	}
}
